server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

eureka:
  instance:
    prefer-ip-address: true
    instance-id: kaveesha-server:config-server:8888
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
